version: '3.7'

services:
  proftpd:
    build:
      context: ./proFTPD      
      args:
        MAIN_USER: vinicius
        MAIN_USER_PASSWORD: 123
        FTP_LIST: "user:123"
        USERADD_OPTIONS: "-o --gid 33 --uid 33"
    hostname: sftp_server
    container_name: sftp_server
    restart: unless-stopped
    networks:
      sftp_server-net:
        ipv4_address: 172.100.13.6
    volumes:
      - ./proFTPD/etc/proftpd:/etc/proftpd
    #   - ./proFTPD/etc/ssh:/etc/ssh

networks:
  sftp_server-net:
    ipam:
      driver: default
      config:
        - subnet: 172.100.13.0/24